<?php

declare(strict_types=1);

namespace App\Livewire\Admin\Categories;

use App\Livewire\Concerns\HasToast;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Layout;
use Livewire\Attributes\On;
use Livewire\Component;
use Livewire\WithPagination;

/**
 * Livewire component for managing blog post categories.
 *
 * Provides CRUD operations for categories including creating, editing,
 * and deleting categories with validation and safeguards against
 * deleting categories that have associated posts.
 */
#[Layout('components.layouts.app')]
final class Index extends Component
{
    use HasToast;
    use WithPagination;

    public bool $showModal = false;

    public bool $showDeleteModal = false;

    public ?int $editingCategoryId = null;

    public ?int $deletingCategoryId = null;

    public ?string $deletingCategoryName = null;

    public string $name = '';

    public string $slug = '';

    public string $description = '';

    public string $color = '#3b82f6';

    public string $search = '';

    public string $lastAutoGeneratedSlug = '';

    protected $queryString = [
        'search' => ['except' => ''],
    ];

    /**
     * Handle the modal-closed event from Alpine.
     */
    #[On('modal-closed')]
    public function closeModal(): void
    {
        $this->resetForm();
        $this->cancelDelete();
        $this->showDeleteModal = false;
    }

    /**
     * Watcher for the showModal property to reset form when closed.
     */
    public function updatedShowModal(bool $value): void
    {
        if (! $value) {
            $this->resetForm();
        }
    }

    /**
     * Reset the form fields and state.
     */
    public function resetForm(): void
    {
        $this->reset(['editingCategoryId', 'name', 'slug', 'description', 'color', 'showModal', 'lastAutoGeneratedSlug']);
        $this->resetValidation();
    }

    /**
     * Open the modal form for creating a new category.
     *
     * Resets the form fields and displays the category creation modal.
     */
    public function createCategory(): void
    {
        $this->resetForm();
        $this->showModal = true;
    }

    /**
     * Open the modal form for editing an existing category.
     *
     * Loads the category data into the form fields and displays the modal.
     *
     * @param  int  $id  The ID of the category to edit.
     */
    public function editCategory(int $id): void
    {
        $category = Category::findOrFail($id);
        $this->editingCategoryId = $category->id;
        $this->name = $category->name;
        $this->slug = $category->slug;
        $this->description = $category->description ?? '';
        $this->color = $category->color ?? '#3b82f6';
        $this->lastAutoGeneratedSlug = $category->slug;
        $this->showModal = true;
    }

    /**
     * Auto-generate the slug when the name field is updated during creation.
     *
     * Only generates the slug automatically if the current slug matches the
     * previously auto-generated one or is empty.
     */
    public function updatedName(): void
    {
        $autoGeneratedSlug = Str::slug($this->name);

        // For new categories, if slug is empty or matches previous auto-gen slug
        if ($this->editingCategoryId === null && (empty($this->slug) || $this->slug === $this->lastAutoGeneratedSlug)) {
            $this->slug = $autoGeneratedSlug;
            $this->lastAutoGeneratedSlug = $autoGeneratedSlug;
        }
    }

    /**
     * Reset pagination when search is updated.
     */
    public function updatedSearch(): void
    {
        $this->resetPage();
    }

    /**
     * Validate and save the category (create or update).
     *
     * Validates the name and slug fields, ensuring slug uniqueness,
     * then creates a new category or updates the existing one.
     */
    public function saveCategory(): void
    {
        $this->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => [
                'required',
                'string',
                'max:255',
                Rule::unique('categories', 'slug')->ignore($this->editingCategoryId),
            ],
            'description' => ['nullable', 'string', 'max:1000'],
            'color' => ['required', 'string', 'regex:/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'],
        ]);

        $data = [
            'name' => $this->name,
            'slug' => $this->slug,
            'description' => $this->description,
            'color' => $this->color,
        ];

        if ($this->editingCategoryId) {
            $category = Category::findOrFail($this->editingCategoryId);
            $category->update($data);
            $this->toastSuccess('Category updated successfully.');
        } else {
            Category::create($data);
            $this->toastSuccess('Category created successfully.');
        }

        $this->showModal = false;
        $this->resetForm();
    }

    /**
     * Set the category ID pending deletion to show the confirmation dialog.
     *
     * @param  int  $id  The ID of the category to confirm deletion for.
     */
    public function confirmDelete(int $id): void
    {
        $category = Category::findOrFail($id);
        $this->deletingCategoryId = $id;
        $this->deletingCategoryName = $category->name;
        $this->showDeleteModal = true;
    }

    /**
     * Cancel the pending category deletion and dismiss the confirmation dialog.
     */
    public function cancelDelete(): void
    {
        $this->deletingCategoryId = null;
        $this->deletingCategoryName = null;
        $this->showDeleteModal = false;
    }

    /**
     * Delete the category pending deletion.
     *
     * Prevents deletion if the category has any associated posts.
     */
    public function deleteCategory(): void
    {
        if ($this->deletingCategoryId === null) {
            return;
        }

        $category = Category::withCount('posts')->findOrFail($this->deletingCategoryId);

        if ($category->posts_count > 0) {
            $this->toastError("Cannot delete category with {$category->posts_count} attached post(s).");
            $this->deletingCategoryId = null;
            $this->showDeleteModal = false;

            return;
        }

        $category->delete();
        $this->deletingCategoryId = null;
        $this->deletingCategoryName = null;
        $this->showDeleteModal = false;
        $this->toastSuccess('Category deleted successfully.');
    }

    /**
     * Render the categories index view with all categories and their post counts.
     */
    public function render(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        $categories = Category::withCount('posts')
            ->when($this->search, fn ($query) => $query->where('name', 'like', "%{$this->search}%")
                ->orWhere('slug', 'like', "%{$this->search}%")
            )
            ->orderBy('name')
            ->paginate(10);

        return view('livewire.admin.categories.index', [
            'categories' => $categories,
        ]);
    }
}
