<div class="flex flex-col gap-10">
    <!-- Header -->
    <div class="flex flex-col gap-2">
        <h1 class="text-3xl font-black tracking-tight text-on-surface-strong dark:text-on-surface-dark-strong">
            {{ __('Welcome back,') }} {{ auth()->user()->name }} 👋
        </h1>
        <p class="text-on-surface/60 dark:text-on-surface-dark/60 font-medium">
            {{ __('Here is what is happening with your platform today.') }}
        </p>
    </div>

    <!-- Stats Cards -->
    <div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
        <x-stat-card
            :label="__('Total Users')"
            :value="number_format($totalUsers)"
            color="primary"
            :href="route('admin.users.index')"
            change="+12%"
            trend="up"
        >
            <x-slot:icon>
                <x-icons.users variant="outline" size="md" />
            </x-slot>
        </x-stat-card>

        <x-stat-card
            :label="__('Total Posts')"
            :value="number_format($totalPosts)"
            color="info"
            change="+5%"
            trend="up"
        >
            <x-slot:icon>
                <x-icons.document-text variant="outline" size="md" />
            </x-slot>
        </x-stat-card>

        <x-stat-card
            :label="__('Published')"
            :value="number_format($publishedPosts)"
            color="success"
            change="Keep it up!"
            trend="neutral"
        >
            <x-slot:icon>
                <x-icons.check-circle variant="outline" size="md" />
            </x-slot>
        </x-stat-card>

        @if ($paymentsEnabled)
            <x-stat-card
                :label="__('Subscriptions')"
                :value="number_format($activeSubscriptions)"
                color="primary"
                :href="route('admin.payments')"
                change="+3%"
                trend="up"
            >
                <x-slot:icon>
                    <x-icons.credit-card variant="outline" size="md" />
                </x-slot>
            </x-stat-card>

            <x-stat-card
                :label="__('Monthly Revenue')"
                :value="'$' . number_format($monthlyRevenue / 100, 2)"
                color="success"
                :href="route('admin.payments')"
                change="+24%"
                trend="up"
            >
                <x-slot:icon>
                    <x-icons.currency-dollar variant="outline" size="md" />
                </x-slot>
            </x-stat-card>
        @endif
    </div>

    <!-- Charts -->
    <div class="grid gap-8 lg:grid-cols-2">
        <x-card padding="false" class="overflow-hidden">
            <x-slot name="header">
                <div class="flex flex-col">
                    <span class="text-sm font-bold text-on-surface-strong dark:text-on-surface-dark-strong">{{ __('User Growth') }}</span>
                    <span class="text-xs text-on-surface/50">{{ __('New registrations over the last 30 days') }}</span>
                </div>
            </x-slot>
            <div class="p-6">
                <div id="user-chart" class="min-h-[300px]"></div>
            </div>
        </x-card>

        <x-card padding="false" class="overflow-hidden">
            <x-slot name="header">
                <div class="flex flex-col">
                    <span class="text-sm font-bold text-on-surface-strong dark:text-on-surface-dark-strong">{{ __('AI Token Usage') }}</span>
                    <span class="text-xs text-on-surface/50">{{ __('Total output tokens generated by agents') }}</span>
                </div>
            </x-slot>
            <div class="p-6">
                <div id="token-chart" class="min-h-[300px]"></div>
            </div>
        </x-card>
    </div>

    <!-- Recent Activity -->
    <div class="grid gap-8 lg:grid-cols-2">
        <!-- Recent Users -->
        <x-card padding="false">
            <x-slot name="header">
                <div class="flex items-center justify-between">
                    <span class="text-sm font-bold text-on-surface-strong dark:text-on-surface-dark-strong">{{ __('Newest Members') }}</span>
                    <x-button size="xs" variant="ghost" href="{{ route('admin.users.index') }}">
                        {{ __('View all') }}
                    </x-button>
                </div>
            </x-slot>
            <div class="divide-y divide-outline dark:divide-outline-dark">
                @forelse ($recentUsers as $user)
                    <div class="flex items-center gap-4 px-6 py-4 transition-colors hover:bg-surface-alt/30 dark:hover:bg-surface-dark/30">
                        <x-avatar :src="$user->avatarUrl()" :initials="$user->initials()" size="md" />
                        <div class="flex-1 min-w-0">
                            <p class="text-sm font-semibold text-on-surface-strong dark:text-on-surface-dark-strong truncate">
                                {{ $user->name }}
                            </p>
                            <p class="text-xs text-on-surface/60 dark:text-on-surface-dark/60 truncate">{{ $user->email }}</p>
                        </div>
                        @php
                            $roleName = $user->roles->first()?->name ?? 'user';
                        @endphp
                        <x-badge
                            :variant="$roleName === 'admin' ? 'primary' : ($roleName === 'editor' ? 'info' : 'default')"
                            size="sm"
                        >
                            {{ ucfirst($roleName) }}
                        </x-badge>
                    </div>
                @empty
                    <div class="p-6 text-center text-sm text-on-surface/50">{{ __('No users yet.') }}</div>
                @endforelse
            </div>
        </x-card>

        <!-- Recent Posts -->
        <x-card padding="false">
            <x-slot name="header">
                <div class="flex items-center justify-between">
                    <span class="text-sm font-bold text-on-surface-strong dark:text-on-surface-dark-strong">{{ __('Latest Posts') }}</span>
                </div>
            </x-slot>
            <div class="divide-y divide-outline dark:divide-outline-dark">
                @forelse ($recentPosts as $post)
                    <div class="flex items-center gap-4 px-6 py-4 transition-colors hover:bg-surface-alt/30 dark:hover:bg-surface-dark/30">
                        <div class="flex size-10 items-center justify-center rounded-xl bg-surface-alt dark:bg-surface-dark">
                            <x-icons.document-text size="sm" class="text-on-surface/40" />
                        </div>
                        <div class="flex-1 min-w-0">
                            <p class="text-sm font-semibold text-on-surface-strong dark:text-on-surface-dark-strong truncate">
                                {{ $post->title }}
                            </p>
                            <p class="text-xs text-on-surface/60 dark:text-on-surface-dark/60">
                                {{ __('by') }} {{ $post->user->name }} &middot; {{ $post->created_at->diffForHumans() }}
                            </p>
                        </div>
                        <x-badge :variant="$post->status === 'published' ? 'success' : 'default'" size="sm">
                            {{ ucfirst($post->status) }}
                        </x-badge>
                    </div>
                @empty
                    <div class="p-6 text-center text-sm text-on-surface/50">{{ __('No posts yet.') }}</div>
                @endforelse
            </div>
        </x-card>
    </div>

    @once
        <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    @endonce

    <script>
        function initDashboardCharts() {
            const isDark = document.documentElement.classList.contains('dark');
            const textColor = isDark ? '#94a3b8' : '#64748b';
            const gridColor = isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)';

            const chartOptions = {
                chart: {
                    type: 'area',
                    height: 300,
                    toolbar: { show: false },
                    fontFamily: 'Instrument Sans, sans-serif',
                    animations: { enabled: true, easing: 'easeinout', speed: 800 }
                },
                stroke: { curve: 'smooth', width: 3, lineCap: 'round' },
                fill: {
                    type: 'gradient',
                    gradient: { 
                        shadeIntensity: 1, 
                        opacityFrom: 0.4, 
                        opacityTo: 0, 
                        stops: [0, 90, 100] 
                    }
                },
                dataLabels: { enabled: false },
                grid: { borderColor: gridColor, strokeDashArray: 4 },
                xaxis: {
                    type: 'datetime',
                    labels: { style: { colors: textColor, fontWeight: 600, fontSize: '11px' } },
                    axisBorder: { show: false },
                    axisTicks: { show: false }
                },
                yaxis: {
                    labels: { style: { colors: textColor, fontWeight: 600, fontSize: '11px' } }
                },
                tooltip: {
                    theme: isDark ? 'dark' : 'light',
                    x: { format: 'dd MMM yyyy' }
                }
            };

            const userEl = document.querySelector("#user-chart");
            if (userEl) {
                userEl.innerHTML = '';
                new ApexCharts(userEl, {
                    ...chartOptions,
                    series: [{ name: 'New Users', data: @json(array_combine($userTrend['labels'], $userTrend['data'])) }],
                    colors: ['#6366f1'],
                }).render();
            }

            const tokenEl = document.querySelector("#token-chart");
            if (tokenEl) {
                tokenEl.innerHTML = '';
                new ApexCharts(tokenEl, {
                    ...chartOptions,
                    series: [{ name: 'Tokens', data: @json(array_combine($tokenTrend['labels'], $tokenTrend['data'])) }],
                    colors: ['#10b981'],
                }).render();
            }
        }

        // Initialize on load
        document.addEventListener('DOMContentLoaded', initDashboardCharts);
        
        // Initialize on Livewire navigation
        document.addEventListener('livewire:navigated', initDashboardCharts);

        // Re-initialize when theme changes
        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                if (mutation.attributeName === 'class') {
                    initDashboardCharts();
                }
            });
        });
        observer.observe(document.documentElement, { attributes: true });
    </script>
</div>
